import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Search } from 'lucide-react';
import api from '../../services/api';
import type { Shipment } from '../../types/models';
import { formatPackageSize } from '../../utils/packageSize';

export default function OpsRecordsPage() {
  const [orders, setOrders] = useState<Shipment[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [deliveryType, setDeliveryType] = useState('');
  useEffect(() => { api.get<Shipment[]>('/shipments').then(r => setOrders(r.data)); }, []);
  const rows = useMemo(() => orders.filter(o => (!status || o.status === status) && (!deliveryType || o.deliveryType === deliveryType) && `${o.trackingCode} ${o.senderName} ${o.receiverName} ${o.dropoffLocation}`.toLowerCase().includes(query.toLowerCase())), [orders, query, status, deliveryType]);
  return <div className="page-shell light-shell" style={{ padding: '32px 24px' }}><h1 style={{ marginTop: 0 }}>Order Records</h1><p style={{ color: '#64748b' }}>Search and reference every order, including station handovers.</p>
    <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', margin: '20px 0' }}><div style={{ position: 'relative', flex: '1 1 260px' }}><Search size={17} style={{ position: 'absolute', left: 12, top: 12, color: '#64748b' }} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Order, sender, receiver, location" style={{ width: '100%', boxSizing: 'border-box', padding: '12px 12px 12px 38px', border: '1px solid #cbd5e1', borderRadius: 10 }} /></div><select value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{['awaiting_price','pending','picked_up','in_transit','out_for_delivery','delivered','delayed','failed','cancelled'].map(s => <option key={s}>{s}</option>)}</select><select value={deliveryType} onChange={e => setDeliveryType(e.target.value)}><option value="">All delivery types</option><option value="doorstep">Doorstep</option><option value="station">Station</option></select></div>
    <div style={{ overflowX: 'auto', background: '#fff', border: '1px solid #e2e8f0', borderRadius: 14 }}><table style={{ width: '100%', minWidth: 900, borderCollapse: 'collapse', textAlign: 'left' }}><thead><tr style={{ background: '#f8fafc' }}>{['Order', 'Route', 'Package', 'Delivery', 'Riders', 'Price', 'Status', ''].map(h => <th key={h} style={{ padding: 14, color: '#64748b', fontSize: 12, textTransform: 'uppercase' }}>{h}</th>)}</tr></thead><tbody>{rows.map(o => <tr key={o.id} style={{ borderTop: '1px solid #e2e8f0' }}><td style={{ padding: 14, fontWeight: 700 }}>{o.trackingCode}<div style={{ fontSize: 12, color: '#64748b', fontWeight: 400 }}>{new Date(o.createdAt).toLocaleDateString()}</div></td><td style={{ padding: 14 }}>{o.pickupLocation}<div style={{ color: '#64748b', fontSize: 12 }}>to {o.dropoffLocation}</div></td><td style={{ padding: 14, textTransform: 'capitalize' }}>{o.packageType} · {formatPackageSize(o)}</td><td style={{ padding: 14, textTransform: 'capitalize' }}>{o.deliveryType}{o.stationLocation && <div style={{ fontSize: 12, color: '#c2410c' }}>{o.stationLocation}</div>}</td><td style={{ padding: 14 }}>{o.pickupRider?.user.name || '—'}<div style={{ fontSize: 12, color: '#64748b' }}>{o.dropoffRider?.user.name || '—'}</div></td><td style={{ padding: 14 }}>GHS {Number(o.deliveryFee).toFixed(2)}</td><td style={{ padding: 14 }}>{o.status.replaceAll('_', ' ')}</td><td style={{ padding: 14 }}><Link to={`/ops/tracking/${o.trackingCode}`}>Details</Link></td></tr>)}</tbody></table></div>
  </div>;
}

